layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
      - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
    instagram: naveen_robotic
  # keybase: your_username
    linkedin: naveen-sakthivel
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: naveen_robotics
  # unsplash: your_username
  # vk: your_username
    website: https://naveens.co.in
  # youtube: your_username

topics:
  - name: Selenium
    web_url: https://github.com/topics/selenium
    image_url: https://camo.githubusercontent.com/c5ee2f8cb386115bc32259d6a58d863ad9dc2e31/687474703a2f2f7777772e73656c656e69756d68712e6f72672f696d616765732f6269672d6c6f676f2e706e67